lib/awesome_elixir_web/router.ex
defmodule AwesomeElixirWeb.Router do
  @moduledoc """
  Defines application specific pipelines and routes.
  """
  use AwesomeElixirWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :exq_browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  pipeline :exq_router do
    plug ExqUi.RouterPlug, namespace: "exq"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :guardian_common do
    plug AwesomeElixirWeb.Guardian.CommonPipeline
  end

  pipeline :guardian_authenticated do
    plug AwesomeElixirWeb.Guardian.AuthenticatedPipeline
  end

  pipeline :guardian_not_authenticated do
    plug AwesomeElixirWeb.Guardian.NotAuthenticatedPipeline
  end

  pipeline :as_admin do
    plug AwesomeElixirWeb.Plugs.AuthenticatedAsAdmin
  end

  scope "/", AwesomeElixirWeb do
    pipe_through [:browser, :guardian_common]

    get "/", CatalogController, :index
  end

  scope "/", AwesomeElixirWeb do
    pipe_through [:browser, :guardian_common, :guardian_authenticated]

    get "/profile", ProfileController, :show
  end

  scope "/api" do
    pipe_through [:api, :guardian_common]

    forward "/graphql", Absinthe.Plug, schema: AwesomeElixirWeb.Schema
  end

  scope "/auth", AwesomeElixirWeb do
    pipe_through [:browser, :guardian_common, :guardian_authenticated]

    get "/logout", AuthController, :logout
  end

  scope "/auth", AwesomeElixirWeb do
    pipe_through [:browser, :guardian_common, :guardian_not_authenticated]

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/exq", ExqUi do
    pipe_through [:exq_browser, :guardian_common, :guardian_authenticated, :as_admin, :exq_router]
    forward "/", RouterPlug.Router, :index
  end
end

lib/awesome_elixir_web/views/layout_view.ex
defmodule AwesomeElixirWeb.LayoutView do
  @moduledoc """
  Implements `Layout` view helpers.
  """
  use AwesomeElixirWeb, :view

  @doc """
  Render notification block according to flash value.
  """
  @spec show_notification(Plug.Conn.t()) :: Plug.Conn.t()
  def show_notification(conn) do
    conn
    |> get_flash()
    |> flash_message()
  end

  defp flash_message(%{"info" => message}) do
    render("notification.html", class: "primary", message: message)
  end

  defp flash_message(%{"error" => message}) do
    render("notification.html", class: "danger", message: message)
  end

  defp flash_message(%{"success" => message}) do
    render("notification.html", class: "success", message: message)
  end

  defp flash_message(_), do: nil
end

lib/awesome_elixir_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Awesome Elixir</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
<%= render("navigation.html", conn: @conn, min_stars_filter_list: min_stars_filter_list(), params: filtered_params(@conn), current_user: current_user(@conn)) %>
<%= show_notification(@conn) %>
<%= render @view_module, @view_template, assigns %>
<%= render("footer.html", conn: @conn, last_updated_at: last_updated_at()) %>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>

lib/awesome_elixir_web/templates/layout/footer.html.eex
    <footer class="fixed-bottom text-right" style="margin-right: 2em; padding-bottom: 1em;">
      <span class="outdated">
        <a href="/doc/index.html" target="_blank">View docs (<%= app_version() %>)</a>.
        <span id="lastUpdateAt">Last updated at: <%= @last_updated_at %></span>
        &nbsp;<a class="github-button" href="https://github.com/unitymind/awesome-elixir-app" data-icon="octicon-star" data-show-count="true" aria-label="Star unitymind/awesome-elixir-app on GitHub">Star</a>
      </span>
    </footer>

lib/awesome_elixir_web/templates/layout/navigation.html.eex
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Awesome Elixir</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
        <%= for {key, value} <- @min_stars_filter_list do %>
          <li class="nav-item <%= if(@params.min_stars == key and @conn.request_path != Routes.profile_path(@conn, :show), do: "active") %>">
            <a class="nav-link filter-link" href="<%= Routes.catalog_path(@conn, :index, %{@params | min_stars: key}) |> raw %>">&ge;<%= value %>&nbsp;⭐</a>
          </li>
        <% end %>
        </ul>

        <ul class="navbar-nav ml-auto">
        <%= if is_nil(@current_user) do %>
          <li class="nav-item">
            <a class="nav-link"  href="<%= Routes.auth_path(@conn, :request, "github") |> raw %>">Login via GitHub</a>
          <li>
        <% else %>
          <li class="nav-item <%= if(@conn.request_path == Routes.profile_path(@conn, :show), do: "active") %>">
            <a class="nav-link"  href="<%= Routes.profile_path(@conn, :show) |> raw %>">Your Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"  href="<%= Routes.auth_path(@conn, :logout) |> raw %>">Logout</a>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>

lib/awesome_elixir_web/templates/layout/notification.html.eex
<div class="alert alert-<%= @class %> alert-dismissible fade show text-center" role="alert" style="margin-top: 2.3em; margin-bottom: -3.0em;">
  <%= @message %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>